{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ $.Values.namespace }}"
  name: ingress-nginx
  labels:
    app: lovechedule-alb-ingress-public
    group: lovechedule
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: app
                port:
                  number: 32080
          {{- end }}
    {{- end }}
{{/*  {{- if .Values.ingress.tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range .Values.ingress.tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range .hosts }}*/}}
{{/*        - {{ . }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ .secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}
{{- end }}
