{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ $.Values.namespace }}"
  name: ingress-nginx
  labels:
    app: lovechedule-alb-ingress-public
    group: lovechedule
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/network-type: "public"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-arn: arn:aws:elasticloadbalancing:ap-northeast-2:327066177061:loadbalancer/app/lc-lb/a1b15c8679030a60
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: app
                port:
                  number: 32080
          {{- end }}
    {{- end }}
{{/*  {{- if .Values.ingress.tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range .Values.ingress.tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range .hosts }}*/}}
{{/*        - {{ . }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ .secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}
{{- end }}
