apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: lovechedule
data:
  mongo-root-username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
type: Opaque
